euromilhoes/euroapp/urls.py
from django.urls import path
from . import views

app_name = 'euroapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('gerar_chave/', views.gerar_chave, name='gerar_chave'),
    path('visualizar_chaves/', views.visualizar_chaves, name='visualizar_chaves'),
]

euromilhoes/euromilhoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('euromilhoes/', include('euroapp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

euromilhoes/euroapp/models.py
from django.db import models

class Chave(models.Model):
    numeros = models.CharField(max_length=100)
    estrelas = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.numeros

euromilhoes/euroapp/views.py
from django.shortcuts import render, redirect
from .models import Chave
import random

def index(request):
    return render(request, 'euroapp/index.html')

def gerar_chave(request):
    numeros = [str(i) for i in range(1, 51)]  # Lista de números de 1 a 50
    estrelas = [str(i) for i in range(1, 13)]  # Lista de estrelas de 1 a 12

    chave = Chave(numeros=', '.join(random.sample(numeros, 5)), estrelas=', '.join(random.sample(estrelas, 2)))
    chave.save()

    context = {
        'chave': chave,
    }

    return render(request, 'euroapp/gerar_chave.html', context)

def visualizar_chaves(request):
    chaves = Chave.objects.all()

    context = {
        'chaves': chaves,
    }

    return render(request, 'euroapp/visualizar_chaves.html', context)

euromilhoes/euroapp/templates/euroapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head >
    <meta charset="utf-8">
    <title>GERADOR DE CHAVES DO EUROMILHÕES</title>
    <style>
        body {text-align: center;background-image: url('{% static "images/stars.jpg" %}');background-size: cover;font-family: 'Rubik', sans-serif;color: #E6F2FF;padding: 0;margin: 0;display: flex;flex-direction: column;min-height: 100vh;}

        .image-container {margin-top: 0px;}

        .content-container {font-size: 12px;text-shadow: 3px 3px 3px rgba(0, 0, 0, 0.8);color: #E6F2FF;}

        hr {color: #3399CC;margin: 4px 0;}
        
        .button-container {margin-top: 15px;}

        .button-container a {margin-top: 20px;padding: 10px 20px;background-color: #2979A4;color: #E6F2FF;text-decoration: none;border-radius: 4px;font-size: 26px;width: 500px;box-shadow: 6px 6px 6px rgba(0, 0, 0, 0.6);}

        .image-container:last-child {margin-top: auto;}
        
        .image-container img {width: 100%;display: block;}
        
        .custom-button {display: block;margin: 15px auto;background-color: #2979A4;color: #E6F2FF;text-decoration: none;border-radius: 4px;font-size: 20px;width: 300px;box-shadow: 6px 6px 6px rgba(0, 0, 0, 0.6);}    
    </style>
</head>
<body>
    <div class="image-container">
        <img src="{% static 'images/euromilhoes.jpg' %}" style="width: 100%">
    </div>
    <div class="content-container">
        <h1>GERADOR DE CHAVES DO EUROMILHÕES</h1>
        <hr>
    </div>
    
    {% block content %}
    {% endblock %}
    <div class="image-container">
        <img src="{% static 'images/euromilhoes_bot.jpg' %}" style="width: 100%;">
    </div>
</body>
</html>

euromilhoes/euroapp/templates/euroapp/gerar_chave.html
{% extends 'euroapp/base.html' %}

{% block content %}
    <style>
        body, html {height: 100%;}
        .chaves-container {max-height: 70vh; overflow-y: auto;}
        h1 {font-size: 24px;text-shadow: 3px 3px 3px rgba(0, 0, 0, 0.8)}
        table td {font-size: 20px; padding-left: 15px;text-shadow: 3px 3px 3px rgba(0, 0, 0, 0.8)}
    </style>
    
    <h1>Chave gerada:</h1>
    <hr>
    <div class="chaves-container">
        <TABLE align="center">
            <TR >
                <TD>
                    <TABLE>
                        <TR style="text-align: left;"><TH>Data:</TH><TD> {{chave.data}}</TD></TR>
                        <TR style="text-align: left;"><TH>Números:</TH><TD> {{chave.numeros}}</TD></TR>
                        <TR style="text-align: left;"><TH>Estrelas:</TH><TD> {{chave.estrelas}}</TD></TR>
                        <BR>
                    </TABLE>
                </TD>
            </TR>
        </TABLE>
    </div>
    <div class="button-container">
        <a href="{% url 'euroapp:gerar_chave' %}" class="custom-button">Gerar uma nova chave</a><br>
        <a href="{% url 'euroapp:index' %}" class="custom-button">Voltar à página inicial</a>
    </div>
{% endblock %}

euromilhoes/euroapp/templates/euroapp/index.html
{% extends 'euroapp/base.html' %}

{% block content %}
    <div class="button-container" style="text-align: center;">
        <br>
        <a href="{% url 'euroapp:gerar_chave' %}" class="custom-button">Gerar chave para jogar no Euromilhões</a><br>
        <a href="{% url 'euroapp:visualizar_chaves' %}" class="custom-button">Visualizar todas as chaves já geradas</a>
        <br>
    </div>
{% endblock %}

euromilhoes/euroapp/templates/euroapp/visualizar_chaves.html
{% extends 'euroapp/base.html' %}

{% block content %}
    <style>
        body, html {height: 100%;}
        .chaves-container {max-height: 70vh; overflow-y: auto;}
        h1 {font-size: 24px;text-shadow: 3px 3px 3px rgba(0, 0, 0, 0.8)}
        table td {font-size: 18px; padding-left: 16px;}
    </style>

    <h1>Todas as chaves já geradas:</h1>
    <div class="chaves-container">
        <TABLE align="center">
        {% for chave in chaves %}
            <TR >
                <TD>
                    <TABLE>
                        <TR style="text-align: left;"><TH>Data:</TH><TD> {{chave.data}}</TD></TR>
                        <TR style="text-align: left;"><TH>Números:</TH><TD> {{chave.numeros}}</TD></TR>
                        <TR style="text-align: left;"><TH>Estrelas:</TH><TD> {{chave.estrelas}}</TD></TR>
                        <TR><HR></TR>
                    </TABLE>
                </TD>
            </TR>
        {% empty %}
            <p>Nenhuma chave gerada ainda.</p>
        {% endfor %}
        </TABLE>
    </div>
    <hr>
    <div class="button-container">
        <a href="{% url 'euroapp:index' %}">Voltar à página inicial</a>
    </div>
    <br>
{% endblock %}